### ISSUE TITLE
Missing GCC5 support

### ISSUE THREAD

**Issue by telphan** [embeddedTS/linux-3.14-pxa16x#1]
Trying to compile this linux on linux-3.14-pxa16x under GCC 5.2 will yield the following compile error:

include/linux/compiler-gcc.h:114:30: fatal error: linux/compiler-gcc5.h: No such file or directory compilation terminated.

Copying the file from the linux tree will yield other compile issues.

**Comment by markfeathers** [comment]
Pushed in d8b95c6cf2d26adb43c6b581bd307a99c54ef520

**Comment by telphan** [comment]
This is the output of compiling your current master with gcc 5.2. 
[log.do_compile.22534](https://files.zenhub.io/56de0939601c8dd53dda931d)

**Comment by agherzan** [comment]
In this case adding the gcc5 header was not enough. @markfeathers , were you able to compile the kernel with gcc5 before?

**Comment by telphan** [comment]
I have found the issue, will submit a patch asap.

**Comment by markfeathers** [comment]
I hadn't tried gcc5 before.  We typically lock the compiler for our builds since it seems inevitably new compilers break older kernel builds.  I just tried this patch with a gcc 5, 4.9, and the recommended codesourcery toolchain which all work.  This has been merged.
